### ISSUE TITLE
Adding drop scramble query

### ISSUE THREAD

**Issue by pyongjoo** [mozafari/verdictdb#265]
Interestingly, it looks like we haven't implemented this... Could you add this? FYI, it should also delete the metadata entry, or add a new entry to mark it removed.

**Comment by dongyoungy** [comment]
I guess we should implement three types of queries here:

1. DROP SCRAMBLE <scramble_table> ON <original_table> -> drops a specific scrambled table
2. DROP ALL SCRAMBLE <original_table> -> drops all scrambled table for an original table
3. SHOW SCRAMBLES -> basically shows `verdictdbmeta` table

There is a problem with current metadata entries, because:
1. we should not use DELETE/UPDATE as many HDFS-based DBMS do not support them.
2. we cannot use existing columns to mark the scrambled table as 'deleted'. For example, we may add a new row with 'added_at' column set to NULL for a deleted scrambled table, but if one generates the same scrambled table afterwards, it is hard to distinguish whether it has been deleted or created most recently.

Therefore, we need to add an additional column (say 'deleted' or something like this) in `verdictdbmeta` to check whether the scrambled table has been deleted or not at `added_at` timestamp. ScrambleMetaStore should only return scrambled table entries that have been added later than most recently deleted entry (if one exists) for each <scrambled_table, original_table> pair. 

What do you think?

**Comment by pyongjoo** [comment]
I think the last column is of TEXT type, which is supposed to contain any metadata in JSON format. Maybe, we can use some special key to indicate that this record is for deletion?

**Comment by dongyoungy** [comment]
Oh, you are right. I guess we can simply set it to NULL or some predefined value like 'DELETED'.

**Comment by pyongjoo** [comment]
I think 'DELETED' is good. NULL is always confusing.

**Comment by dongyoungy** [comment]
Got it.

**Comment by pyongjoo** [comment]
Can you release this version to Maven Central as well as on the releases tab?

**Comment by dongyoungy** [comment]
It has been released as v0.5.6.

**Comment by pyongjoo** [comment]
Thanks. Let me close this issue for now. I'll test it in SquirrelSQL.
